// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvironment() {
  return window['go']['main']['App']['GetEnvironment']();
}

export function IFCend() {
  return window['go']['main']['App']['IFCend']();
}

export function IFCinit(arg1, arg2) {
  return window['go']['main']['App']['IFCinit'](arg1, arg2);
}

export function IFCset(arg1, arg2) {
  return window['go']['main']['App']['IFCset'](arg1, arg2);
}
