// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function GetEnvironment():Promise<runtime.EnvironmentInfo>;

export function IFCend():Promise<void>;

export function IFCinit(arg1:Array<string>,arg2:string):Promise<void>;

export function IFCset(arg1:string,arg2:any):Promise<void>;
